name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    env: 
        EVENT: ${{ toJSON( github.event ) }}
        ECR_REPOSITORY: ${{ github.repository.split('/').slice(1).join('/') }}
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
          run: echo "$EVENT"
      
      - name: "Eventos"
        run: echo "$EVENT"
      
      - name: "Repository fullname"
        run: echo "${{ github.repository }}"
        
      - name: 'Repository shortname'
        run: echo "$ECR_REPOSITORY"
        
      - name: "printenv"
        run: printenv
        
      - name: "SHA"
        run: echo "${{ github.sha }}"
        shell: bash
        
      - name: 'GITHUB_REPOSITORY_OWNER'
        run: echo "${{ github.repository.owner }}"
        shell: bash
      
