name: A workflow for my Hello World file
on:
 - push
 - pull_request
 - workflow_dispatch

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    env: 
        EVENT: ${{ toJSON( github.event ) }}
        BU: 'ZAP'
        SQUAD: 'OWNERS'
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
          run: echo "$EVENT"
      
      - name: Fetch Repo Name
        id: repo-name
        run: echo "::set-output name=value::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
      
      - name: "Eventos"
        run: echo "$EVENT"
      
      - name: "Repository fullname"
        run: echo "${{ github.repository }}"
        
      - name: 'Repository shortname'
        run: echo "${{ steps.repo-name.outputs.value }}"
        
      - name: "printenv"
        run: printenv
        
      - name: "SHA"
        run: echo "${{ github.sha }}"
        shell: bash
        
      - name: 'GITHUB_REPOSITORY_OWNER'
        run: echo "${{ github.repository.owner }}"
        shell: bash
  
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Execute Unit Tests
        run: echo "${{ steps.repo-name.outputs.value }}"
    
      
