name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    env: 
        EVENT: ${{ toJSON( github.event ) }}
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
          run: echo "$EVENT"
      
      - name: "Eventos"
        run: echo "$EVENT"
      
      - name: "Reposi"
        run: echo "${{ github.repository }}"
        
      - name: "printenv"
        run: printenv
        
      - name: "SHA"
        run: echo "${{ GITHUB_SHA }}"
        shell: bash
      
