name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
          run: echo "$EVENT"
      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash
      - run: echo "repoName:>>> ${{ env.REPOSITORY_NAME }}"

  print-env:
    runs-on: ubuntu-latest
    name: Print event data
    env: 
        EVENT: ${{ toJSON( github.event ) }}
        run: echo "$EVENT"
